# -*- coding: utf-8 -*-
"""Speech Recognition transcribing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0sdIgyQ-U7lwdu8QF5HW5EGg3K08411
"""

!pip install wikipedia pyjokes pytz

import wikipedia
import pyjokes
import webbrowser
import pytz
from datetime import datetime

def run_alexa():
    command = input("Enter command: ").lower()

    if 'play' in command:
        song = command.replace('play', '').strip()
        print(f"Opening YouTube search for {song}")
        webbrowser.open(f"https://www.youtube.com/results?search_query={song}")

    elif 'time' in command or 'date' in command:
        ist = pytz.timezone('Asia/Kolkata')
        now = datetime.now(ist)

        current_time = now.strftime('%I:%M %p')
        current_date = now.strftime('%d %B %Y')

        print(f"Current date is {current_date}")
        print(f"Current time is {current_time}")

    elif 'who is' in command:
        person = command.replace('who is', '').strip()
        try:
            info = wikipedia.summary(person, 1)
            print(info)
        except:
            print("No information found.")

    elif 'joke' in command:
        print(pyjokes.get_joke())

    else:
        print("Command not recognized.")

while True:
    run_alexa()